modLoader="javafml" 
loaderVersion="[35,)" 
license="Team Novus, All rights reserved"

[[mods]]
    modId = "lovely_llamas"
    version = "1.0.0"
    
    logoFile = "logo.png"
    authors = "Team Novus"
    credits = "Thanks to Orilly, Pugz, and Durger King"
    displayName = "Lovely Llamas"
    description = '''This mod aims to improve Llamas in  Minecraft.'''

[[dependencies.lovely_llamas]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.4,1.16.5)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.lovely_llamas]]
    modId = "forge"
    mandatory = true
    versionRange = "[35.1.4,)"
    ordering = "NONE"
    side = "BOTH"